- AudioCodecs.hh
Attempting to compile with GCC 11.1 yields this error:
```
In file included from AudioCodecs.cc:1:
AudioCodecs.hh:5:55: error: ‘size_t’ has not been declared
5 | std::vector<int16_t> decode_mace(const uint8_t* data, size_t size, bool stereo,
|                                                       ^~~~~~
AudioCodecs.hh:7:55: error: ‘size_t’ has not been declared
7 | std::vector<int16_t> decode_ima4(const uint8_t* data, size_t size, bool stereo);
|                                                       ^~~~~~
AudioCodecs.hh:8:55: error: ‘size_t’ has not been declared
8 | std::vector<int16_t> decode_alaw(const uint8_t* data, size_t size);
|                                                       ^~~~~~
AudioCodecs.hh:9:55: error: ‘size_t’ has not been declared
9 | std::vector<int16_t> …
```
> Fix size_t compile bug with GCC 11.1

- hypercard_dasm.cc
Got the following build error with `g++ (Gentoo 10.2.0-r5 p6) 10.2.0` for file `hypercard_dasm.cc`:
```
hypercard_dasm.cc: In function ‘std::string autoformat_hypertalk(const string&)’:
hypercard_dasm.cc:66:94: error: no matching function for call to ‘transform(std::__cxx11::basic_string<char>::iterator, std::__cxx11::basic_string<char>::iterator, std::__cxx11::basic_string<char>::iterator, <unresolved overloaded function type>)’
66 |       transform(lowercase_line.begin(), lowercase_line.end(), lowercase_line.begin(), tolower);
|                                                                                              ^
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/functional:65,
from /usr/include/phosg/Filesystem.hh:15,
from hypercard_dasm.cc:9: …
```
> Fix build error for hypercard_dasm.cc

- src/QuickDrawFormats.cc
When [Quickdraw](https://computerhistory.org/blog/macpaint-and-quickdraw-source-code/) processes a region, two inversion points at the same location equal no inversion point, so the current implementation is correct, and the TODO isn't necessary 😃
> Handling of duplicate inversion points in region is correct, no need for TODO

- src/resource_dasm.cc
Contrary to APFS, where the resource fork is optional, on HFS+ files always have a resource fork. So don't only check for its existance, but also that it's not empty.
Also removed the shorter `/rsrc` form of accessing the resource fork, as it [was deprecated in MacOS 10.4 and removed in 10.7](https://en.wikipedia.org/wiki/Resource_fork#How_a_resource_fork_is_accessed), and is equivalent to the longer form anyway. It's still recognized when used in the output file name, though. This might not be necessary, depending on whether backwards compatibility with older resource_dasm versions is important or not.
> On HFS+ all files have resource forks, so check the size as well

- src/resource_dasm.cc
Filenames can be formatted with printf-like placeholders (see changes to the help). The old options still exist. The names of generated JSON files will be slightly different from before, though.
Future additional placeholders could be: `%a` for the resource's attributes, `%s` for the resource's size.
> More flexible formatting of the output filenames

- TODO.md
- src/ResourceFile.cc
- src/ResourceFile.hh
- src/SystemTemplates.cc
Starting with System 7, ALRT, DLOG and WIND resources can contain an additional word (correctly aligned) with the alert/dialog/window's positioning (none, center on main screen, stagger relative to parent window etc). To correctly decode this, I added a TMPL type for optional data at the end of the resource.
Left to do: decide how to display the value for positioning, as there are only a few valid ones (see Rez header file `Types.r`).
> Correctly decode positioning of ALRT, DLOG and WIN

- src/Emulators/M68KEmulator.cc
- src/Emulators/M68KEmulator.hh
The 68k disassembler now disassembles the optional symbol at the end of a function. It also skips any constant data following after the symbol. This also reduces the amount of "alternate branches" and ".incomplete" in the disassembler's output.
Tested via resource_dasm on several applications that use the new symbol format. The old formats are untested, but should work.
Left to do:
- Disassemble the constant data as one/several lines of `dc.w xxxx` instead of skipping it, like ResEdit and Resorcerer do. I'm not sure if it's ok with you to return several lines from `disassemble_one`.
- Use the symbol names instead of anonymous labels. I don't pretend to quite understand how the labelling currently works ;-)
> Disassemble MacsBug symbols

- src/ResourceFile.cc
- src/ResourceFile.hh
- src/resource_dasm.cc
Instead of treating characters outside of ASCII-7 as invalid for decoding and filenames, decode them using MacRoman:
1. OSTypes e.g. in FREF. Decoded FREF old: `File type: 0x93436F6E`; new: `File type: 'ìCon' (0x93436F6E)`.
2. Resource type in the output filename. Old: `Icon Dearchiver 4.0.app__x93Dea_0.bin`; new: `Icon Dearchiver 4.0.app_ìDea_0.bin`.
> Decode OSType as MacRoman

- src/QuickDrawEngine.cc
Format the QuickTime codec's OSType as a string, not a number. Before: `(compressed QuickTime data uses codec 57524C45)`; after: `(compressed QuickTime data uses codec 'WRLE' [0x57524C45])`.
The inclusion of `ResourceFile.hh` just for `string_for_resource_type` is a bit ugly; these conversion-to-string functions should probably get their own file.
> Better error message when rendering PICTs with unknown QuickTime codec

- src/ResourceFile.cc
Just some (hopefully clarifying) comments on TMPL-types. The ones about type P100 were derived from experiments with Resorcerer and ResEdit.
> Document TMPL-types a bit more, especially Resorcerer-only ones

- src/resource_dasm.cc
So people don't get a lot of .bmp files when they only want .icns and vice versa.
> Command line switch --icon-family-format to set file format of exported icon families

- src/resource_dasm.cc
A really simple file format. Tested with Photoshop 6.0.1.
> Also store color table as Photoshop .act (color table) file

- src/ResourceFile.cc
Don't repeat array name in array element for better readability. Old:
```
Items: (8 entries)
Items[0]
Bounds: x1=218, y1=132, x2=288, y2=150
Type: 4
Info: 'Save'
Items[1]
Bounds: x1=218, y1=158, x2=288, y2=176
Type: 4
Info: 'Cancel'
```
New:
```
Items: (8 entries)
0:
Bounds: x1=218, y1=132, x2=288, y2=150
Type: 4
Info: 'Save'
1:
Bounds: x1=218, y1=158, x2=288, y2=176
Type: 4
Info: 'Cancel'
```
Put single-line array elements on the same line as the array index for better readability. Old:
```
Number of frames (cursors): 8
Used frame counter: 0
Frames: (EOF-terminated list)
0:
CURS resource ID: 4
1:
CURS resource ID: -6078
2:
CURS resource ID: -6077
...
```
New:
```
Number of frames (cursors): 8
Used frame counter: 0
Frames: (EOF-terminated list)
0: CURS resource ID: 4
1: CURS resource ID: …
```
> Improvements to readability of TMPL lists (YMMV):

- CMakeLists.txt
- README.md
- src/Cli.cc
- src/Cli.hh
- src/dupe_finder.cc
- src/resource_dasm.cc
Say you like to collect MacOS classic icons. Say you've collected a lot of them, probably in several files because you can't have more than 2727 resources in a single one[*] and also want a semblance of order. Now you want to know if you have any duplicates in your collection, so you can delete them.
That's why this tool exists. It looks for duplicates in one or several resource files, lists them and optionally deletes them.
[*] You can cram in slightly over 5400, but then ResEdit seems to randomly delete resources when pasting more.
> New tool: dupe_finder

- src/Cli.cc
- src/Cli.hh
- src/ResourceFile.cc
- src/ResourceFile.hh
- src/ResourceIDs.hh
- src/dupe_finder.cc
- src/resource_dasm.cc
- resource_dasm now supports ID ranges. This probably changed the interactions between resource_dasm's various include/exclude options a bit. Honestly, I think they have become too complicated and should be simplified in some way.
- IDs/ID ranges can be excluded instead of included by prefixing them with `~` (`!` can't be used because it clashes with the shell's history expansion).
- ResourceIDs's constructor takes an `enum` instead of a `bool` to get rid of unwanted implicit conversions (e.g. from pointers) to `bool`.
> More flexible selection of resource types and IDs

- CMakeLists.txt
- README.md
- TODO.md
- src/DataCodecs/Codecs.hh
- src/DataCodecs/PackBits.cc
- src/icon_dearchiver.cc
I've been working on this on and off for the past few months, and frankly I'm sick of it ;-) It supports both Icon Archiver 2 and 4 (the only versions in existence as far as I know). I tested it with some huge archives (30k+ icons), and it seems to work ok. The TODOs refer mostly to possible additional features.
As you can see from the `???`s in the code, a fair amount of the archive's format is still a mystery. But as long as it works...
(note to self: don't use it to dearchive (unarchive?) 9000+ icons into a single folder, and then open that folder in OS 9's Finder...)
> new tool: icon_dearchiver: dearchive Icon Archiver's icon archives

- src/Emulators/MemoryContext.cc
If only clang warned when using the wrong printf format even when it's accidentally correct (such as `%lX` on a platform where `size_t` happens to have the same size as `unsigned long`)...
> Fix for #53

- src/ResourceFile.cc
- src/ResourceFile.hh
- previously: 0..32768, -32768..-1
- now: -32768..32767
> Correctly sort resource IDs

- CMakeLists.txt
This is mainly for myself, but might be useful to others. The symlink requirement is unfortunate, but could be remedied by renaming phosg's `src` directory to `phosg`.
> Specify location of phosg library

- src/ResourceFile.cc
- src/ResourceFile.hh
- src/SystemTemplates.cc
This is mainly an experiment, motivated by issue #59. All builds were done with XCode 11 on macOS 10.14.6.
Default build:
- shared_ptr: 4493304
- unique_ptr: 4391488
Default build + strip:
- shared_ptr: 2315096
- unique_ptr: 2212112
So with and without debug symbols, using `unique_ptr` in resource templates makes the executable ~100K smaller.
(the changes in `SystemTemplates.cc` are a bit more involved, because `initializer_list`'s elements aren't movable :rolleyes:)
> Resource Templates: replace shared_ptr with unique_ptr to see how the size of the `resource_dasm` executable changes
